#!/bin/bash

export STOPTS="-av --delete --delete-delay --stats --progress"
export BASE="/export/big/mirror/pub"
export SCRIPTS="/export/big/mirror/scripts"
export PATTERNS="/export/big/mirror/scripts/patterns"
export RSYNC="/export/software/mirror/bin/rsync"
export LOGFILE="/export/software/mirror/var/log/mirror.log"
export LOCKDIR="/export/software/mirror/var/run/mirror"
export VERBOSE=yes

for script in $@
  do start="`date +%s` (`date +%Y.%m.%d\ %H:%M:%S`)"
  lock=$LOCKDIR/$script.lock
  if [ -f $lock ]; then
    echo $start -- skipping $script:cli >> $LOGFILE
    echo "skipping $script"
  else
    touch $lock
    echo $start -- beginning $script:cli >> $LOGFILE
    if [ "x$@" = "x$script" ]
    then
      bash $SCRIPTS/$script 2>&1
    else
      bash $SCRIPTS/$script 2>&1 | unbuffer -p sed "s/^/$script: /"
    fi
    echo "`date +%s` (`date +%Y.%m.%d\ %H:%M:%S`) -- finished $script:cli from $start" >> $LOGFILE
    rm -f $lock
  fi
done
