#!/bin/bash

export STOPTS="-nav --stats --progress --delete --delete-delay"
export BASE="/export/big/mirror/pub"
export SCRIPTS="/export/big/mirror/scripts"
export PATTERNS="/export/big/mirror/scripts/patterns"
export RSYNC="/export/software/mirror/bin/rsync"
export LOGFILE="/export/software/mirror/var/log/mirror.log"

for script in $@
do start="`date +%s` (`date -u +%Y.%m.%d\ %H:%M:%S`)"
#echo $start -- beginning $script:cli >> $LOGFILE
bash $SCRIPTS/$script
#echo "`date +%s` (`date -u +%Y.%m.%d\ %H:%M:%S`) -- finished $script:cli from $start" >> $LOGFILE
done
